---
apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraftcontroller
  namespace: dc1
  annotations:
    platform.confluent.io/broker-id-offset: '910'
spec:
  replicas: 2
  clusterID: ZjczNWY5ZjItZTA3OS00Nw
  controllerQuorumVoters:
    - brokerEndpoint: kraftcontroller-0-internal.dc1:9074
      nodeId: 910
    - brokerEndpoint: kraftcontroller-1-internal.dc1:9074
      nodeId: 911
    - brokerEndpoint: kraftcontroller-0-internal.dc2:9074
      nodeId: 920
  oneReplicaPerNode: true
  dataVolumeCapacity: 1G
  podTemplate:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
  image:
    application: confluentinc/cp-server:7.9.1
    init: confluentinc/confluent-init-container:2.11.1
  configOverrides:
    server:
      - confluent.consumer.lag.emitter.enabled=true
      - broker.rack=dc1
      - config.providers=file,dir,env
      - config.providers.dir.class=org.apache.kafka.common.config.provider.DirectoryConfigProvider
      - config.providers.env.class=org.apache.kafka.common.config.provider.EnvVarConfigProvider
      - config.providers.file.class=org.apache.kafka.common.config.provider.FileConfigProvider
      - confluent.metadata.topic.replication.factor=4
      - confluent.metadata.topic.min.insync.replicas=3
      - confluent.balancer.topic.replication.factor=4
      - confluent.security.event.logger.exporter.kafka.topic.replicas=4
      - default.replication.factor=4
      - min.insync.replicas=3
      - offsets.topic.replication.factor=4
      - offsets.topic.min.isr=3
      - transaction.state.log.replication.factor=4
      - transaction.state.log.min.isr=3
      - replica.selector.class=org.apache.kafka.common.replica.RackAwareReplicaSelector
      - confluent.link.metadata.topic.replication.factor=4
      - confluent.link.metadata.topic.min.isr=3
      - confluent.license.topic.replication.factor=4
      - confluent.license.topic.min.isr=3
      - confluent.cluster.link.metadata.topic.replication.factor=4
      - confluent.cluster.link.metadata.topic.min.isr=3
---
apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraftcontroller
  namespace: dc1
  annotations:
    platform.confluent.io/broker-id-offset: '910'
spec:
  replicas: 2
  controllerQuorumVoters:
    - brokerEndpoint: kraftcontroller-0-internal.dc1:9074
      nodeId: 910
    - brokerEndpoint: kraftcontroller-1-internal.dc1:9074
      nodeId: 911
    - brokerEndpoint: kraftcontroller-0-internal.dc2:9074
      nodeId: 920
  oneReplicaPerNode: true
  dataVolumeCapacity: 1G
  podTemplate:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
  image:
    application: confluentinc/cp-server:7.9.1
    init: confluentinc/confluent-init-container:2.11.1
  configOverrides:
    server:
      - confluent.consumer.lag.emitter.enabled=true
      - broker.rack=dc1
      - config.providers=file,dir,env
      - config.providers.dir.class=org.apache.kafka.common.config.provider.DirectoryConfigProvider
      - config.providers.env.class=org.apache.kafka.common.config.provider.EnvVarConfigProvider
      - config.providers.file.class=org.apache.kafka.common.config.provider.FileConfigProvider
      - confluent.metadata.topic.replication.factor=4
      - confluent.metadata.topic.min.insync.replicas=3
      - confluent.balancer.topic.replication.factor=4
      - confluent.security.event.logger.exporter.kafka.topic.replicas=4
      - default.replication.factor=4
      - min.insync.replicas=3
      - offsets.topic.replication.factor=4
      - offsets.topic.min.isr=3
      - transaction.state.log.replication.factor=4
      - transaction.state.log.min.isr=3
      - replica.selector.class=org.apache.kafka.common.replica.RackAwareReplicaSelector
      - confluent.link.metadata.topic.replication.factor=4
      - confluent.link.metadata.topic.min.isr=3
      - confluent.license.topic.replication.factor=4
      - confluent.license.topic.min.isr=3
      - confluent.cluster.link.metadata.topic.replication.factor=4
      - confluent.cluster.link.metadata.topic.min.isr=3
---
apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraftcontroller
  namespace: dc2
  annotations:
    platform.confluent.io/broker-id-offset: '920'
spec:
  replicas: 1
  clusterID: ZjczNWY5ZjItZTA3OS00Nw
  controllerQuorumVoters:
    - brokerEndpoint: kraftcontroller-0-internal.dc1:9074
      nodeId: 910
    - brokerEndpoint: kraftcontroller-1-internal.dc1:9074
      nodeId: 911
    - brokerEndpoint: kraftcontroller-0-internal.dc2:9074
      nodeId: 920
  oneReplicaPerNode: true
  dataVolumeCapacity: 1G
  podTemplate:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
  image:
    application: confluentinc/cp-server:7.9.1
    init: confluentinc/confluent-init-container:2.11.1
  configOverrides:
    server:
      - confluent.consumer.lag.emitter.enabled=true
      - broker.rack=dc2
      - config.providers=file,dir,env
      - config.providers.dir.class=org.apache.kafka.common.config.provider.DirectoryConfigProvider
      - config.providers.env.class=org.apache.kafka.common.config.provider.EnvVarConfigProvider
      - config.providers.file.class=org.apache.kafka.common.config.provider.FileConfigProvider
      - confluent.metadata.topic.replication.factor=4
      - confluent.metadata.topic.min.insync.replicas=3
      - confluent.balancer.topic.replication.factor=4
      - confluent.security.event.logger.exporter.kafka.topic.replicas=4
      - default.replication.factor=4
      - min.insync.replicas=3
      - offsets.topic.replication.factor=4
      - offsets.topic.min.isr=3
      - transaction.state.log.replication.factor=4
      - transaction.state.log.min.isr=3
      - replica.selector.class=org.apache.kafka.common.replica.RackAwareReplicaSelector
      - confluent.link.metadata.topic.replication.factor=4
      - confluent.link.metadata.topic.min.isr=3
      - confluent.license.topic.replication.factor=4
      - confluent.license.topic.min.isr=3
      - confluent.cluster.link.metadata.topic.replication.factor=4
      - confluent.cluster.link.metadata.topic.min.isr=3
