---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: dc1
  annotations:
    platform.confluent.io/broker-id-offset: "100"
spec:
  replicas: 3
  oneReplicaPerNode: true
  rackAssignment:
    nodeLabels:
      - topology.kubernetes.io/zone
  image:
    application: confluentinc/cp-server:7.9.1
    init: confluentinc/confluent-init-container:2.11.1
  dataVolumeCapacity: 10Gi
  podTemplate:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
        namespace: dc1
  configOverrides:
    server:
      - confluent.consumer.lag.emitter.enabled=true
      - confluent.consumer.lag.emitter.interval.ms=10000
      - default.replication.factor=6
      - min.insync.replicas=3
      - confluent.metadata.topic.replication.factor=6
      - confluent.metadata.topic.min.insync.replicas=3
      - confluent.balancer.topic.replication.factor=6
      - offsets.topic.replication.factor=6
      - offsets.topic.min.isr=3
      - transaction.state.log.replication.factor=6
      - confluent.link.metadata.topic.replication.factor=6
      - confluent.tier.metadata.replication.factor=6
      - confluent.license.topic.replication.factor=6
      - confluent.cluster.link.metadata.topic.replication.factor=6
      - confluent.metadata.topic.min.insync.replicas=3
      - confluent.security.event.logger.exporter.kafka.topic.replicas=3
      - event.logger.exporter.kafka.topic.replicas=3
      - replica.selector.class=org.apache.kafka.common.replica.RackAwareReplicaSelector
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: dc2
  annotations:
    platform.confluent.io/broker-id-offset: "200"
spec:
  replicas: 3
  oneReplicaPerNode: true
  rackAssignment:
    nodeLabels:
      - topology.kubernetes.io/zone
  image:
    application: confluentinc/cp-server:7.9.1
    init: confluentinc/confluent-init-container:2.11.1
  dataVolumeCapacity: 10Gi
  podTemplate:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
        namespace: dc2
  configOverrides:
    server:
      - confluent.consumer.lag.emitter.enabled=true
      - confluent.consumer.lag.emitter.interval.ms=10000
      - default.replication.factor=6
      - min.insync.replicas=3
      - confluent.metadata.topic.replication.factor=6
      - confluent.metadata.topic.min.insync.replicas=3
      - confluent.balancer.topic.replication.factor=6
      - offsets.topic.replication.factor=6
      - offsets.topic.min.isr=3
      - transaction.state.log.replication.factor=6
      - confluent.link.metadata.topic.replication.factor=6
      - confluent.tier.metadata.replication.factor=6
      - confluent.license.topic.replication.factor=6
      - confluent.cluster.link.metadata.topic.replication.factor=6
      - confluent.metadata.topic.min.insync.replicas=3
      - confluent.security.event.logger.exporter.kafka.topic.replicas=3
      - event.logger.exporter.kafka.topic.replicas=3
      - replica.selector.class=org.apache.kafka.common.replica.RackAwareReplicaSelector
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: dc3
  annotations:
    platform.confluent.io/broker-id-offset: "300"
spec:
  replicas: 3
  oneReplicaPerNode: true
  rackAssignment:
    nodeLabels:
      - topology.kubernetes.io/zone
  image:
    application: confluentinc/cp-server:7.9.1
    init: confluentinc/confluent-init-container:2.11.1
  dataVolumeCapacity: 10Gi
  podTemplate:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
        namespace: dc3
  configOverrides:
    server:
      - confluent.consumer.lag.emitter.enabled=true
      - confluent.consumer.lag.emitter.interval.ms=10000
      - default.replication.factor=6
      - min.insync.replicas=3
      - confluent.metadata.topic.replication.factor=6
      - confluent.metadata.topic.min.insync.replicas=3
      - confluent.balancer.topic.replication.factor=6
      - offsets.topic.replication.factor=6
      - offsets.topic.min.isr=3
      - transaction.state.log.replication.factor=6
      - confluent.link.metadata.topic.replication.factor=6
      - confluent.tier.metadata.replication.factor=6
      - confluent.license.topic.replication.factor=6
      - confluent.cluster.link.metadata.topic.replication.factor=6
      - confluent.metadata.topic.min.insync.replicas=3
      - confluent.security.event.logger.exporter.kafka.topic.replicas=3
      - event.logger.exporter.kafka.topic.replicas=3
      - replica.selector.class=org.apache.kafka.common.replica.RackAwareReplicaSelector