---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  license:
    globalLicense: true
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:7.9.1
    init: confluentinc/confluent-init-container:2.11.1
  dataVolumeCapacity: 10Gi
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.dc1.svc.cluster.local:9071
